### ISSUE TITLE
ImportError: No module named cv2

### ISSUE THREAD

**Issue by Apetited** [jiong3/glocutch#1]
I don't think this is an issue with this script in particular, but I can't import the cv2 module. I've installed OpenCV using brew, but Python can't seem to access it. Any advice would be appreciated.

**Comment by jiong3** [comment]
Are you sure the python you use is the brew python and not the system python?

I didn't expect anyone to use this script anymore, since the pdfs haven't been sold for a long time and the script only works with a specific version of the pdfs. Is it really what you need?

**Comment by Apetited** [comment]
I ended up writing a new script using OCR. Requires more manual processing after but the end result is better. Thanks anyway!
